---
name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.PAT_LIFTER_API_WRAPPER }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PAT_LIFTER_API_WRAPPER }}
          changelog_increment_filename: CHANGELOG.MD
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "CHANGELOG.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: slack-release-nofication
        uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: "#releases"
          payload: |
            {
              "text": "## `lifter-api-wrapper` Release",
              "attachments": [
                {
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "${{ env.REVISION }}",
                      "short": false,
                      "value": "https://pypi.org/project/lifter-api-wrapper/"
                    },
                    {
                      "title": "Changelog",
                      "short": false,
                      "value": "https://github.com/WeightliftingNZ/lifter-api-wrapper/blob/main/CHANGELOG.md"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
